### ISSUE TITLE
Missing xsd2json utility

### ISSUE THREAD

**Issue by moltar** [Mermade/jgeXml#10]
Docs mention `xsd2json` utility, but none are installed.

Thanks!

**Comment by MikeRalphson** [comment]
Thanks for raising this. Do you mean no command script is installed if you install `jgexml` globally?

**Comment by moltar** [comment]
Yeah, there are no command scripts. I installed locally, but it shouldn't matter, I think?

There needs to be a `bin` key in the `package.json` file.

Docs: https://docs.npmjs.com/files/package.json#bin

**Comment by MikeRalphson** [comment]
Ok, let me move some things around and rename some others. This was the first piece of Node.js code I ever wrote and it's not been touched much since. I'll ping you when a new version has been released.

**Comment by MikeRalphson** [comment]
`v0.4.0` has separate `cli` and `examples` directories, and the three cli utilities are defined in the `package.json` `bin` map.

**Comment by moltar** [comment]
Awesome. Thank you for the speedy fix :)
