### ISSUE TITLE
xsd2json prints "false"

### ISSUE THREAD

**Issue by moltar** [Mermade/jgeXml#11]
Running `xsd2json` on [this file](https://raw.githubusercontent.com/dmichael/amazon-mws/master/examples/xsd/amzn-base.xsd), and the CLI just outputs `false`.

Any ideas?

Thanks!

**Comment by MikeRalphson** [comment]
Two fixes in `v0.4.1`:
- Now throws an error if it can't detect an XSD schema rather than returning false
- `xmlns` prefix autodetection added for XML Schema

**Comment by moltar** [comment]
Wow, that is pretty amazing. Works super well now!!

**Comment by moltar** [comment]
Thank you!

**Comment by MikeRalphson** [comment]
No problem.
